
import "./globals.css";
import "@repo/ui/globals.css";
import { ThemeProvider } from "@repo/ui/components/theme-provider";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  auth,
  dashboard,
  children,
}: {
  auth: React.ReactNode;
  dashboard: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class" enableSystem disableTransitionOnChange>
          {/* {auth} */}
          {dashboard}
          {/* {children} */}
        </ThemeProvider>
      </body>
    </html>
  );
}
